baseURL = "https://chemicalcheese.net/"
languageCode = "en-us"
title = "ChemicalCheese"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Posts about homelabs, networking, security, and other random technology topics."

  # Metadata mostly used in document's head
  description = "Random posts about anything IT related"
  keywords = "security homelab virtualization networking"
  images = [""]

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  defaultTheme = "dark"

[permalinks]
  posts = "/post/:year/:month/:title/"
  # Hack to get /post/:year and /post/:year/:month to render content
  year = "/post/:title/"
  month = "/post/:title/"

[taxonomies]
  category = "categories"
  tag      = "tags"
  series   = "series"
  post     = "posts"
  # Hack to get /:year and /:year/:month to render content
  year = "year"
  month = "month"

[languages]
  [languages.en]
    title = "ChemicalCheese"
    homeSubtitle = "Posts about homelabs, networking and other random technology related topics."
    keywords = "security homelab virtualization networking"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    readMore = "Continue reading"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
      logoMark = "ChemicalCheese$"
      logoCursorColor = "grey"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
#  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"
